# Generated by Django 4.0.4 on 2022-04-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_code', models.CharField(blank=True, max_length=255, null=True)),
                ('dict_detail_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dict_info', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dict_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_code', models.CharField(blank=True, max_length=255, null=True)),
                ('dict_type', models.CharField(blank=True, max_length=255, null=True)),
                ('dict_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dict_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hour', models.CharField(blank=True, max_length=255, null=True)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'project_join',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('join_time', models.DateTimeField(blank=True, null=True)),
                ('remove_flag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_info', models.TextField(blank=True, null=True)),
                ('project_concact', models.CharField(blank=True, max_length=255, null=True)),
                ('project_concact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('project_icon', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('service_obj', models.CharField(blank=True, max_length=255, null=True)),
                ('project_area', models.CharField(blank=True, max_length=255, null=True)),
                ('project_mem', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateField(blank=True, null=True)),
                ('end_time', models.DateField(blank=True, null=True)),
                ('check_status', models.CharField(blank=True, max_length=255, null=True)),
                ('remove_flag', models.CharField(blank=True, max_length=255, null=True)),
                ('service_hour', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'team_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_name', models.CharField(blank=True, max_length=255, null=True)),
                ('id_card', models.CharField(blank=True, max_length=255, null=True)),
                ('pwd', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('user_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('qq', models.CharField(blank=True, max_length=255, null=True)),
                ('wechat', models.CharField(blank=True, max_length=255, null=True)),
                ('hometown', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('service_area', models.CharField(blank=True, max_length=255, null=True)),
                ('user_icon', models.TextField(blank=True, null=True)),
                ('remove_flag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'volunteer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('comment_content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volunteer_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cloth_size', models.CharField(blank=True, max_length=255, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=255, null=True)),
                ('service_exp', models.TextField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('service_prof', models.CharField(blank=True, max_length=255, null=True)),
                ('advanced', models.CharField(blank=True, max_length=255, null=True)),
                ('team_invite_proj', models.CharField(blank=True, max_length=255, null=True)),
                ('team_invite', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'volunteer_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerRank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('punctual', models.CharField(blank=True, max_length=255, null=True)),
                ('service_atitude', models.CharField(blank=True, max_length=255, null=True)),
                ('profess_level', models.CharField(blank=True, max_length=255, null=True)),
                ('train_time', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'volunteer_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_login_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_pwd', models.CharField(blank=True, max_length=255, null=True)),
                ('team_concact', models.CharField(blank=True, max_length=255, null=True)),
                ('team_concact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('team_icon', models.TextField(blank=True, null=True)),
                ('team_intro', models.TextField(blank=True, null=True)),
                ('team_create_time', models.DateTimeField(blank=True, null=True)),
                ('remove_flag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'volunteer_team',
                'managed': False,
            },
        ),
    ]
