# Generated by Django 4.0.4 on 2022-05-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'managed': False, 'verbose_name': '志愿者信息', 'verbose_name_plural': '志愿者信息'},
        ),
    ]
